export const works = [
  {
    pageName: 'return-to-blank',
    name: 'return-to-blank',
    imgSrc: 'return-to-blank.png',
    tags: ['Interactive', 'Side Project'],
  },
  {
    pageName: 'memory',
    name: 'MEMORY',
    imgSrc: 'pnudt12.png',
    tags: ['Web', 'Interactive', 'Design', 'Frontend', 'Side Project'],
  },
  {
    pageName: 'catch-the-candy',
    name: 'CATCH THE CANDY',
    imgSrc: 'catchTheCandy.png',
    tags: ['Web', 'Interactive', 'Side Project'],
  },
  {
    pageName: 'portfolio',
    name: 'portfolio',
    imgSrc: 'portfolio.png',
    tags: ['Web', 'Interactive', 'Design', '3D', 'Side Project'],
  },
  {
    pageName: 'launchpad',
    name: 'launchpad',
    imgSrc: 'nijoow-launchpad.png',
    tags: ['Web', 'Interactive', 'Frontend', 'Design', 'Side Project'],
  },
  // {
  //   pageName: 'nijoow-vintage',
  //   name: 'nijoow-vintage',
  //   imgSrc: 'nijoow-vintage.png',
  //   tags: ['Web', 'Frontend', 'Design', 'Side Project'],
  // },
  // {
  //   pageName: 'love-predictor',
  //   name: 'Love-Predictor',
  //   imgSrc: 'ai-love-predictor.png',
  //   tags: ['Web', 'Frontend', 'Side Project'],
  // },
  {
    pageName: 'treenow',
    name: 'Treenow',
    imgSrc: 'treenow.png',
    tags: ['Web', 'Frontend', 'Business Project'],
  },
  {
    pageName: 'svg-drawing',
    name: 'svg-drawing',
    imgSrc: 'nijoow-drawing.png',
    tags: ['Web', 'Frontend', 'Interactive', 'Design', 'Side Project'],
  },
  {
    pageName: 'cusmetic',
    name: 'cusmetic',
    imgSrc: 'cusmetic.png',
    tags: ['Web', 'Frontend', 'Business Project'],
  },
  {
    pageName: 'nijoow-shopping-mall',
    name: 'nijoow-shopping-mall',
    imgSrc: 'nijoow-shopping-mall.png',
    tags: ['Web', 'Frontend', 'Backend', 'Design', 'Side Project'],
  },
  {
    pageName: 'moharu',
    name: 'moharu',
    imgSrc: 'moharu.png',
    tags: ['Web', 'Frontend', 'Side Project'],
  },
  // {
  //   pageName: 'television',
  //   name: 'television',
  //   imgSrc: 'television.png',
  //   tags: ['Web', 'Frontend', '3D', 'Side Project'],
  // },
  {
    pageName: 'fromyou',
    name: 'fromyou',
    imgSrc: 'fromyou.png',
    tags: [
      'Web',
      'Frontend',
      'Interactive',
      'Design',
      'Business Project',
      'Freelancer',
    ],
  },
  {
    pageName: 'atop-dms',
    name: 'ATOP.DMS',
    imgSrc: 'atop-dms/main.png',
    tags: ['Web', 'Frontend', 'Business Project'],
  },
  // {
  //   pageName: 'x-pixel',
  //   name: 'X-PIXEL',
  //   imgSrc: 'x-pixel.png',
  //   tags: ['Web', 'Frontend', 'Business Project'],
  // },
  {
    pageName: 'moimcity',
    name: '모임특별시',
    imgSrc: 'moimcity/moimcity.png',
    tags: ['Web', 'Frontend', 'Business Project', 'Freelancer'],
  },
  {
    pageName: 'fromis9-stickers',
    name: '프로미스나인 스티커 꾸미기',
    imgSrc: 'fromis9-stickers.png',
    tags: ['Web', 'Interactive', 'Design', 'Frontend', 'Side Project'],
  },
];
