export const works = [
  {
    pageName: 'return-to-blank',
    name: 'return-to-blank',
    imgSrc: 'return-to-blank.png',
    tags: ['Interactive'],
  },
  {
    pageName: 'memory',
    name: 'MEMORY',
    imgSrc: 'pnudt12.png',
    tags: ['Interactive', 'Web', 'Design', 'Frontend'],
  },
  {
    pageName: 'catch-the-candy',
    name: 'CATCH THE CANDY',
    imgSrc: 'catchTheCandy.png',
    tags: ['Interactive', 'Web'],
  },
  {
    pageName: 'portfolio',
    name: 'portfolio',
    imgSrc: 'portfolio.png',
    tags: ['Web', 'Interactive', 'Design', '3D'],
  },
  {
    pageName: 'launchpad',
    name: 'launchpad',
    imgSrc: 'nijoow-launchpad.png',
    tags: ['Interactive', 'Frontend', 'Design'],
  },
  {
    pageName: 'nijoow-vintage',
    name: 'nijoow-vintage',
    imgSrc: 'nijoow-vintage.png',
    tags: ['Web', 'Frontend', 'Design'],
  },
  {
    pageName: 'love-predictor',
    name: 'Love-Predictor',
    imgSrc: 'ai-love-predictor.png',
    tags: ['Frontend'],
  },
  {
    pageName: 'treenow',
    name: 'Treenow',
    imgSrc: 'treenow.png',
    tags: ['Web', 'Frontend'],
  },
  {
    pageName: 'svg-drawing',
    name: 'svg-drawing',
    imgSrc: 'nijoow-drawing.png',
    tags: ['Frontend', 'Interactive', 'Web', 'Design'],
  },
  {
    pageName: 'cusmetic',
    name: 'cusmetic',
    imgSrc: 'cusmetic.png',
    tags: ['Web', 'Frontend'],
  },
  {
    pageName: 'nijoow-shopping-mall',
    name: 'nijoow-shopping-mall',
    imgSrc: 'nijoow-shopping-mall.png',
    tags: ['Web', 'Frontend', 'Backend', 'Design'],
  },
  {
    pageName: 'moharu',
    name: 'moharu',
    imgSrc: 'moharu.png',
    tags: ['Web', 'Frontend'],
  },
  {
    pageName: 'television',
    name: 'television',
    imgSrc: 'television.png',
    tags: ['Web', 'Frontend', '3D'],
  },
]
