export const works = [
  {
    pageName: 'return-to-blank',
    name: 'return-to-blank',
    imgSrc: 'return-to-blank.webp',
    tags: ['Interactive', 'Side Project'],
  },
  {
    pageName: 'memory',
    name: 'MEMORY',
    imgSrc: 'pnudt12.webp',
    tags: ['Web', 'Interactive', 'Design', 'Frontend', 'Side Project'],
  },
  {
    pageName: 'catch-the-candy',
    name: 'CATCH THE CANDY',
    imgSrc: 'catchTheCandy.webp',
    tags: ['Web', 'Interactive', 'Side Project'],
  },
  {
    pageName: 'portfolio',
    name: 'portfolio',
    imgSrc: 'portfolio.webp',
    tags: ['Web', 'Interactive', 'Design', '3D', 'Side Project'],
  },
  {
    pageName: 'launchpad',
    name: 'launchpad',
    imgSrc: 'nijoow-launchpad.webp',
    tags: ['Web', 'Interactive', 'Frontend', 'Design', 'Side Project'],
  },
  // {
  //   pageName: 'love-predictor',
  //   name: 'Love-Predictor',
  //   imgSrc: 'ai-love-predictor.webp',
  //   tags: ['Web', 'Frontend', 'Side Project'],
  // },
  {
    pageName: 'treenow',
    name: 'Treenow',
    imgSrc: 'treenow.webp',
    tags: ['Web', 'Frontend', 'Business Project'],
  },
  {
    pageName: 'svg-drawing',
    name: 'svg-drawing',
    imgSrc: 'nijoow-drawing.webp',
    tags: ['Web', 'Frontend', 'Interactive', 'Design', 'Side Project'],
  },
  {
    pageName: 'cusmetic',
    name: 'cusmetic',
    imgSrc: 'cusmetic.webp',
    tags: ['Web', 'Frontend', 'Business Project'],
  },
  // {
  //   pageName: 'nijoow-shopping-mall',
  //   name: 'nijoow-shopping-mall',
  //   imgSrc: 'nijoow-shopping-mall.webp',
  //   tags: ['Web', 'Frontend', 'Backend', 'Design', 'Side Project'],
  // },
  {
    pageName: 'moharu',
    name: 'moharu',
    imgSrc: 'moharu.webp',
    tags: ['Web', 'Frontend', 'Side Project'],
  },

  {
    pageName: 'atop-dms',
    name: 'ATOP.DMS',
    imgSrc: 'atop-dms/main.webp',
    tags: ['Web', 'Frontend', 'Business Project'],
  },
  {
    pageName: 'fromyou',
    name: '독자시점주의 From You',
    imgSrc: 'fromyou.webp',
    tags: [
      'Web',
      'Frontend',
      'Interactive',
      'Design',
      'Business Project',
      'Freelancer',
    ],
  },
  {
    pageName: 'moimcity',
    name: '모임특별시',
    imgSrc: 'moimcity/moimcity.webp',
    tags: ['Web', 'Frontend', 'Business Project', 'Freelancer'],
  },
  {
    pageName: 'fromis9-stickers',
    name: '프로미스나인 스티커 꾸미기',
    imgSrc: 'fromis9-stickers.webp',
    tags: ['Web', 'Interactive', 'Design', 'Frontend', 'Side Project'],
  },
  {
    pageName: 'ml3yp',
    name: 'Midnight Lo-fi 3D Youtube Player',
    imgSrc: 'ml3yp.webp',
    tags: ['Web', 'Frontend', '3D', 'Interactive', 'Design', 'Side Project'],
  },
  {
    pageName: 'lessor-panda-village',
    name: '레서판다 빌리지',
    imgSrc: 'lessor-panda-village.webp',
    tags: ['Web', 'Interactive', '3D', 'Side Project', 'Frontend'],
  },
];
